### ISSUE TITLE
Aula E12 sin red. Y altavoces no van bien 

### ISSUE THREAD

**Issue by diego-ies** [IES-LaSenia/incidencias#116]
El ordenador del aula E12 no tiene Red. Aparentemente será la tarjeta integrada de la placa.

SOLUCIONES:
- Poner una tarjeta de Red externa.

Los altavoces tienen mucho ruido de estática.

**Comment by aberlanas** [comment]
Cambiar también el teclado.

**Comment by diego-ies** [comment]
Teclado cambiado. Y Maria José ha apuntado en la libreta del electricista el ruido de los altavoces.
