### ISSUE TITLE
Aula 17

### ISSUE THREAD

**Issue by aberlanas** [IES-LaSenia/incidencias#119]
crec que a l'aula 17 no funciona el so, o almenys jo no l'he conseguit fer anar...
he intentat ficar a la tutoria un vídeo però no hi ha hagut èxit per escoltar-lo. M'he fixat que el vídeo tinguès el volum activat, així com l'ordinador i l'interruptor dels altaveus, no se si calia tenir en compte alguna cosa més.

**Comment by diego-ies** [comment]
Acabo de revisar el sonido y sí que funcionan los altavoces.

**Comment by diego-ies** [comment]
Se puede cerrar el issue.
