### ISSUE TITLE
Tecnologia - Scratch Online

### ISSUE THREAD

**Issue by aberlanas** [IES-LaSenia/incidencias#124]
Además, con el ordenador 6 (subiendo, enfrente), no se puede conectar a scratch online, he intentado actualizar el navegador sin éxito.

**Comment by diego-ies** [comment]
Se ha añadido un 1GB de RAM al ordenador. Ahora tiene 2GB de RAM.

Se ha actualizado la versión de Firefox, y se puede acceder a la web de Scratch para crear proyectos. Se ha puesto un enlace directo en el escritorio.

ESTE TICKET SE PUEDE CERRAR.
