### ISSUE TITLE
[AP 1] No va sonido

### ISSUE THREAD

**Issue by aberlanas** [IES-LaSenia/incidencias#76]
No va el sonido en el AP 1

**Comment by aberlanas** [comment]
Seguimos recibiendo incidencias

no funciona el audio del ordenador de la prefabricada nº1 (donde recibe las clases el grupo E31). Si es posible solucionarlo sería de gran ayuda.

**Comment by anabel-aracil** [comment]
Solucionado por Elias y Diego
